proxmox:
  hosts:
    PROXMOX_IP:
      ansible_user: PROXMOX_USERNAME
      proxmox:
        api_user: PROXMOX_USER
        api_password: PROXMOX_PASSWORD
        api_host: PROXMOX_IP
        node_name: PROXMOX_NODE_NAME
      runner:
        template_name: VM_TEMPLATE_NAME
        gw: NETWORK_DEFAULT_GATEWAY
        ip: RUNNER_IP
        vm_name: RUNNER_NAME
        registration_token: RUNNER_TOKEN